site_name: Corpusama - a corpus creation package

watch:
- corpusama

theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - navigation.footer
    - content.code.copy
  palette:
    primary: black

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - footnotes
  - attr_list
  - tables
  - md_in_html
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
  - mkdocstrings
  - search

nav:
  - index.md
  - Corpus:
    - corpus/about.md
    - corpus/archive.md
    - corpus/attribute.md
    - corpus/corpus.md
    - corpus/inspect.md
    - corpus/stanza.md
    - corpus/tagset.md
    - corpus/vertical.md
  - Database:
    - database/about.md
  - Source:
    - source/about.md
    - source/call.md
    - source/pdf.md
    - source/reliefweb.md
  - Utilities:
    - util/about.md
    - util/convert.md
    - util/dataclass.md
    - util/decorator.md
    - util/flatten.md
    - util/io.md
    - util/langid.md
    - util/parallel.md
    - util/util.md
