source: reliefweb
schema: corpusama/database/schema/reliefweb.sql
db_name: data/reliefweb_2000+.db
text_column: body_html
attribute_file: corpusama/source/params/rw-attribute.yml
quota: 1000
wait_dict: {"0": 1, "5": 49, "10": 99, "20": 499, "30": null}
parameters:
  filter:
    conditions:
    - field: format
      negate: true
      value:
      - Map
      - Interactive
      - Infographic
      - Other
    - field: date
      value:
        from: '2000-01-01T00:00:00+00:00'
    operator: AND
  fields:
    exclude: [body]
  limit: 1000
  offset: 0
  profile: full
  slim: 1
  sort:
  - date.changed:asc
